version: '3.7'

services:
  graphium:
    build: .
    container_name: graphium-server
    environment:
      - "db.url=jdbc:postgresql://database:5432/graphium"
      - "db.username=graphium"
      - "db.password=graphium"
      - "CATALINA_OPTS=-Xms512m -Xmx2048m"
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: "mdillon/postgis:11"
    container_name: graphium-database
    environment:
      - "POSTGRES_USER=graphium"
      - "POSTGRES_PASSWORD=graphium"
      - "POSTGRES_DB=graphium"
    ports:
      - "5432:5432"
    volumes:
      - ./postgis/db/composite/create_graphium_database.sql:/docker-entrypoint-initdb.d/create_graphium_database.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: